// generated by volcano.

package cn.com.heaton.blelibrary;

public final class R {

    public static final class string {
        public static final int lib_name = _RM.string.lib_name;
        public static final int ota_error = _RM.string.ota_error;
        public static final int update_cancel = _RM.string.update_cancel;
        public static final int update_retry = _RM.string.update_retry;
        public static final int updating = _RM.string.updating;
    }

    private static final class _RM extends rM.aixtr.R { }
}
